version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - print: echo "Hello world"
workflows:
  version: 2
  tests:
    jobs:
      - build
      - test
